name: testflight

on:
  push:
    tags:
      - 'Release_*'

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Decode signing certificate into a file
        env:
          CERTIFICATE_BASE64: ${{ secrets.APPLE_KEY_ID }}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > signing-cert.p12

      - name: Install CocoaPods dependencies
        run: |
          pod install
          pod update

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'
      
      - name: Install Bundle
        run: bundle install

      - name: Update Fastlane
        run: bundle update fastlane

      - name: Upload iOS binary to TestFlight
        env:
          APPLE_ID: '${{ secrets.APPLE_ID }}'
          ITC_TEAM_ID: '${{ secrets.ITC_TEAM_ID }}'
          DEV_PORTAL_TEAM_ID: '${{ secrets.DEV_PORTAL_TEAM_ID }}'
          KEYCHAIN_NAME: '${{ secrets.KEYCHAIN_NAME }}'
          KEYCHAIN_PASSWORD: '${{ secrets.KEYCHAIN_PASSWORD }}'
          APPLE_KEY_ID: '${{ secrets.APPLE_KEY_ID }}'
          APPLE_ISSUER_ID: '${{ secrets.APPLE_ISSUER_ID }}'
          APPLE_KEY_CONTENT: '${{ secrets.APPLE_KEY_CONTENT }}'
          GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
        run: bundle exec fastlane tf
